require('plugins')
require('config')
require('keybindings')
require('staline_setup')
require('stabline_setup')
require('web_devicons')
-- require('bufferline_setup')
require('nvimtree_setup')
require('telescope_setup')
require('alpha_setup')
-- require('colorizer_setup')
require('treesitter_setup')
require('which_key_setup')
require('which_key_maps')
require('comment_setup')
require('luasnip_setup')
require('indent_blankline_setup')
require('twilight_setup')
require('zenmode_setup')
require('cmp_setup')
require("luasnip.loaders.from_vscode").lazy_load()
require('autopairs_setup')
require('nnn_nvim_setup')
require('numb_setup')
require('toggleterm_setup')
require('abbreviations')
require('ccc_setup')
require('nvim_surround_setup')
