theme = "onedark"

[editor]
auto-completion = true
auto-format = true
bufferline = "multiple"
color-modes = true
completion-trigger-len = 2
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
line-number = "relative"
mouse = true
scrolloff = 15

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "spacer", "position", "spacer", "position-percentage"]
separator = "⋄"
mode.normal = "☯ "
mode.insert = "🖌 "
mode.select = "✀ "

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = true

[editor.search]
smart-case = true

[editor.indent-guides]
render = true  
character = "⸽"
skip-levels = 1  

[editor.whitespace]


# KEY REMAPPING
[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-s = ":w"

[keys.insert]
j = { k = "normal_mode" } # maps jk to exit insert mode
